const test = require('node:test'), assert = require('node:assert/strict');
const fs = require('fs'), os = require('os'), path = require('path');
const dir = fs.mkdtempSync(path.join(os.tmpdir(),'pulse-tests-'));
process.env.DB_PATH=path.join(dir,'test.db');process.env.NODE_ENV='test';
process.env.ADMIN_EMAIL='test-admin@example.test';process.env.ADMIN_DEFAULT_PASSWORD='FixturePasswordOnly!';
process.env.SESSION_SECRET='fixture-session-only';process.env.ANTHROPIC_API_KEY='fixture';
const db=require('../db/db'), bcrypt=require('bcryptjs');
const pass='FixturePasswordOnly!';
for(const [id,name,opening] of [['a','Centre Alpha',0],['b','Centre Beta',0],['open','Centre Opening',1]]) db.prepare('INSERT INTO centres(owna_id,name,capacity,opening) VALUES(?,?,100,?)').run(id,name,opening);
for(const role of ['viewer','centre','exec','ops_manager','admin','unassigned','invalid','unknown']) db.prepare('INSERT INTO users(email,name,password_hash,role,location_id) VALUES(?,?,?,?,?)').run(role+'@example.test',role,bcrypt.hashSync(pass,4),['unassigned','invalid'].includes(role)?'centre':role,role==='centre'?'a':role==='invalid'?'missing':null);
for(const id of ['a','b']) db.prepare('INSERT INTO daily_metrics(owna_id,metric_date,capacity,booked) VALUES(?,?,100,50)').run(id,'2026-09-07');
const app=require('../server');
const ask=require('../services/ai-ask');ask.ask=async(q,h,scope)=>({answer:scope||'all',toolCalls:[]});
const originalFetch=global.fetch;
let server,base;
async function login(role){const r=await originalFetch(base+'/login',{method:'POST',body:new URLSearchParams({email:role+'@example.test',password:pass}),redirect:'manual'});assert.equal(r.status,302);return r.headers.get('set-cookie').split(';')[0];}
async function request(url,cookie,body){return originalFetch(base+url,{headers:{cookie,...(body?{'content-type':'application/x-www-form-urlencoded'}:{})},method:body?'POST':'GET',body:body?new URLSearchParams(body):undefined,redirect:'manual'});}
test('Phase 0 regression suite',async(t)=>{
 server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));base='http://127.0.0.1:'+server.address().port;
 try {
 await t.test('unassigned, stale assignment and unknown roles cannot read any dashboard route',async()=>{for(const role of ['unassigned','invalid','unknown']){const c=await login(role);for(const p of ['/','/pc','/ask','/centre/a']){const r=await request(p,c);assert.ok([302,403].includes(r.status),role+' '+p+' '+r.status);}}});
 await t.test('centre scope holds for overview, direct URLs, writes and AI tools',async()=>{const c=await login('centre');const r=await request('/',c);assert.equal(r.status,200);assert.ok(!(await r.text()).includes('Centre Beta'));assert.equal((await request('/centre/b',c)).status,403);assert.equal((await request('/wages',c)).status,403);assert.equal((await request('/action-plans/edit',c,{owna:'b',month:'2026-09'})).status,403);const a=await request('/ask',c,{question:'all centres'});assert.equal((await a.json()).answer,'a');const tools=require('../services/ai-tools');assert.ok(tools.runTool('waitlist',{},'missing').error);assert.ok(tools.runTool('waitlist',{centre:'Beta'},'a').error);});
 await t.test('viewer cannot read identified pages including opening-centre bypass',async()=>{const c=await login('viewer');for(const p of ['/exits','/centre/a/pipeline','/qc','/action-plans','/admin/feedback'])assert.equal((await request(p,c)).status,403,p);const r=await request('/centre/open',c);assert.equal(r.status,302);assert.match(r.headers.get('location'),/^\/pipeline/);assert.equal((await request('/centre/a',c)).status,200);});
 await t.test('password reset and deletion invalidate existing sessions',async()=>{const c=await login('exec');db.prepare('UPDATE users SET password_hash=? WHERE email=?').run(bcrypt.hashSync('ChangedFixturePassword!',4),'exec@example.test');assert.equal((await request('/',c)).status,302);const v=await login('viewer');db.prepare('DELETE FROM users WHERE email=?').run('viewer@example.test');assert.equal((await request('/',v)).status,302);});
 await t.test('action-plan fields survive saving and injected content is escaped',async()=>{const c=await login('admin'),evil='<img src=x onerror=alert(1)>';const data={owna:'a',month:'2026-09',overall:evil,context:evil,f_urgent_0:'Safety',a_urgent_0:evil,o_urgent_0:'Owner',s_urgent_0:'Underway',due_date_urgent_0:'2026-10-01',progress_urgent_0:'In progress',outcome_urgent_0:'Safer practice'};assert.equal((await request('/action-plans/edit',c,data)).status,302);const item=db.prepare('SELECT * FROM action_plan_items').get();assert.equal(item.due_date,'2026-10-01');assert.equal(item.progress,'In progress');const view=await request('/action-plans?owna=a&month=2026-09',c);assert.equal(view.status,200);const html=await view.text();assert.ok(!html.includes(evil));assert.ok(html.includes('&lt;img'));assert.equal((await request('/action-plans/edit?owna=a',c)).status,200);assert.equal((await request('/action-plans/edit',c,{owna:'bad',month:'2026-99'})).status,400);});
 await t.test('backup restores correctly and rejects tampering, wrong password and overwrite',async()=>{const {backup,restore}=require('../services/backup');const enc=path.join(dir,'backup.enc'),restored=path.join(dir,'restored.db'),secret='Random-test-passphrase-long-enough';await assert.rejects(backup(db,enc,''));assert.ok(!fs.existsSync(enc));await backup(db,enc,secret);assert.throws(()=>restore(enc,restored,'wrong-password-but-long-enough'));assert.ok(!fs.existsSync(restored));restore(enc,restored,secret);const D=require('better-sqlite3');const d=new D(restored,{readonly:true});assert.equal(d.pragma('integrity_check',{simple:true}),'ok');assert.equal(d.prepare('SELECT COUNT(*) n FROM centres').get().n,3);d.close();assert.throws(()=>restore(enc,restored,secret));const bytes=fs.readFileSync(enc);bytes[bytes.length-1]^=1;fs.writeFileSync(enc,bytes);assert.throws(()=>restore(enc,path.join(dir,'tampered.db'),secret));});
 await t.test('payrun pagination reads beyond 30 and rejects repeated pages',async()=>{const {eh}=require('../services/eh');const records=Array.from({length:231},(_,id)=>({id:id+1}));global.fetch=async(url)=>{const skip=Number(new URL(url).searchParams.get('$skip'));return {ok:true,text:async()=>JSON.stringify(records.slice(skip,skip+100))};};assert.equal((await eh.payRuns()).length,231);global.fetch=async()=>({ok:true,text:async()=>JSON.stringify(records.slice(0,100))});await assert.rejects(eh.payRuns(),/pagination/);global.fetch=originalFetch;});
 await t.test('same payment date, different periods; gross mismatch leaves old data intact',async()=>{const {eh}=require('../services/eh');const {runLabourSnapshot}=require('../services/eh-labour');eh.hasCreds=()=>true;eh.locations=async()=>[{id:10,name:'Organisation'},{id:11,parentId:10,name:'Centre Alpha'},{id:12,parentId:11,name:'Room 1'}];eh.allEmployees=async()=>[{id:1,jobTitle:'Educator'}];eh.payRuns=async()=>[{id:1,isFinalised:true,datePaid:'2026-09-08',payPeriodEnding:'2026-09-06'},{id:2,isFinalised:true,datePaid:'2026-09-08',payPeriodEnding:'2026-08-30'},{id:3,isFinalised:true,datePaid:'2026-09-09',payPeriodEnding:'2026-09-06'}];eh.earnings=async id=>({payRunId:id,earningsLines:{1:[{id,locationId:12,locationName:'Room 1',payCategoryName:'Ordinary',units:2,earnings:id*100,super:12}]}});eh.runTotals=async id=>({payRunId:id,payRunTotals:{1:{grossEarnings:id*100}}});const r=await runLabourSnapshot({weeks:2,log:()=>{}});assert.equal(r.total_wages,600);assert.equal(db.prepare('SELECT total_wages FROM labour_weekly WHERE week_ending=?').get('2026-09-06').total_wages,400);assert.equal(db.prepare('SELECT total_wages FROM labour_weekly WHERE week_ending=?').get('2026-08-30').total_wages,200);eh.runTotals=async id=>({payRunId:id,payRunTotals:{1:{grossEarnings:999}}});await assert.rejects(runLabourSnapshot({weeks:2,log:()=>{}}),/reconcile/);assert.equal(db.prepare('SELECT SUM(total_wages) n FROM labour_weekly').get().n,600);});
 await t.test('AI budget and cross-origin write protection',async()=>{const c=await login('admin');for(let i=0;i<20;i++)assert.equal((await request('/ask',c,{question:'occupancy'})).status,200);assert.equal((await request('/ask',c,{question:'occupancy'})).status,429);const r=await originalFetch(base+'/feedback',{method:'POST',headers:{cookie:c,origin:'https://untrusted.example','content-type':'application/x-www-form-urlencoded'},body:'message=test',redirect:'manual'});assert.equal(r.status,403);assert.equal((await request('/',c)).headers.get('cache-control'),'no-store');});
 await t.test('employee half-cent rounding reconciles without hiding missing earnings',()=>{const {normaliseRun}=require('../services/eh-labour');const run={id:9,payPeriodEnding:'2026-09-06'};const detail={payRunId:9,earningsLines:{1:[{id:1,locationName:'Alpha',payCategoryName:'Ordinary',earnings:12.345,units:1}]}};const totals={payRunId:9,payRunTotals:{1:{grossEarnings:12.35}}};assert.equal(normaliseRun(run,detail,totals).rows[0].amount,12.35);totals.payRunTotals[1].grossEarnings=12.36;assert.throws(()=>normaliseRun(run,detail,totals),/reconcile/);});
 await t.test('fresh production seed rejects default password and runtime schema survives reopen',()=>{const {spawnSync}=require('child_process');const r=spawnSync(process.execPath,['-e',"require('./db/db')"],{cwd:path.join(__dirname,'..'),env:{...process.env,DB_PATH:':memory:',NODE_ENV:'production',ADMIN_DEFAULT_PASSWORD:'ChangeMe123!'},encoding:'utf8'});assert.equal(r.status,1);const D=require('better-sqlite3');const file=path.join(dir,'restart.db');let d=new D(file);require('../db/init-schema').initSchema(d);d.prepare('INSERT INTO centres(owna_id,name) VALUES(?,?)').run('persist','Persistence fixture');d.close();d=new D(file);require('../db/init-schema').initSchema(d);assert.equal(d.prepare('SELECT COUNT(*) n FROM centres').get().n,1);d.close();});
 await t.test('snapshot records per-source health and surfaces payroll import failures',async()=>{
  const {runSnapshot,errSummary,sourceSyncFor}=require('../services/snapshot');
  const {owna}=require('../services/owna');const {eh}=require('../services/eh');const {lineleader}=require('../services/lineleader');
  assert.equal(errSummary(new Error('EH 500  /api/v2/x\n\n more')),'EH 500 /api/v2/x more');
  assert.equal(errSummary(new Error('x'.repeat(500))).length,240);
  assert.equal(errSummary(new TypeError('bad')),'TypeError: bad');
  assert.equal(errSummary(null),'null');
  // No network: every upstream the snapshot touches is stubbed (the repo .env may hold real credentials).
  lineleader.hasCreds=()=>false;owna.listCentres=async()=>[];owna.listChildren=async()=>[];owna.weeklyRoster=async()=>null;owna.childIncidents=async()=>[];
  eh.hasCreds=()=>true;eh.allEmployees=async()=>[];eh.payRuns=async()=>{throw new Error('EH 502 /api/v2/business/1/payrun');};
  const logs=[];const r1=await runSnapshot({log:(m)=>logs.push(m)});
  assert.equal(r1.status,'partial');
  const run1=db.prepare('SELECT status,note FROM snapshot_runs ORDER BY id DESC LIMIT 1').get();
  assert.equal(run1.status,'partial');assert.match(run1.note,/EH payroll import failed: EH 502 \/api\/v2\/business\/1\/payrun/);
  assert.ok(logs.some(l=>l.includes('EH payroll import failed: EH 502')),'failure reason is logged');
  const p1=sourceSyncFor('eh_labour');assert.equal(p1.status,'error');assert.equal(p1.last_success,null);assert.match(p1.detail,/EH 502/);
  assert.equal(sourceSyncFor('owna').status,'ok');assert.equal(sourceSyncFor('lineleader').status,'skipped');
  const c=await login('admin');let html=await (await request('/wages',c)).text();assert.match(html,/Payroll import failed/);assert.match(html,/EH 502/);assert.match(html,/No wages have been imported yet/);
  html=await (await request('/admin/wage-budget',c)).text();assert.match(html,/Payroll import failed/);
  html=await (await request('/',c)).text();assert.match(html,/partial — EH payroll import failed/);
  // A finalised run that reconciles → status ok, metadata kept.
  eh.locations=async()=>[{id:10,name:'Organisation'},{id:11,parentId:10,name:'Centre Alpha'}];
  eh.payRuns=async()=>[{id:5,isFinalised:true,datePaid:'2026-09-08',payPeriodEnding:'2026-09-06'}];
  eh.earnings=async id=>({payRunId:id,earningsLines:{1:[{id:1,locationId:11,locationName:'Centre Alpha',payCategoryName:'Ordinary',units:8,earnings:300,super:30}]}});
  eh.runTotals=async id=>({payRunId:id,payRunTotals:{1:{grossEarnings:300}}});
  const r2=await runSnapshot({log:()=>{}});assert.equal(r2.status,'ok');
  const p2=sourceSyncFor('eh_labour');assert.equal(p2.status,'ok');assert.ok(p2.last_success);assert.equal(p2.meta.latest_period,'2026-09-06');assert.equal(p2.meta.runs,1);
  html=await (await request('/wages',c)).text();assert.match(html,/Payroll imported/);assert.match(html,/pay periods to 6 Sept? 2026/);
  // A later failure keeps the last-good metadata and says which data is on screen.
  eh.payRuns=async()=>{throw new Error('EH 401 /api/v2/business/1/payrun');};
  await runSnapshot({log:()=>{}});const p3=sourceSyncFor('eh_labour');assert.equal(p3.status,'error');assert.equal(p3.last_success,p2.last_success);assert.equal(p3.meta.latest_period,'2026-09-06');
  html=await (await request('/wages',c)).text();assert.match(html,/Payroll import failed/);assert.match(html,/last successful import/);assert.match(html,/pay periods to 6 Sept? 2026/);
  const st=await request('/admin/status',c);assert.equal(st.status,200);const js=await st.json();assert.ok(js.sources.some(s=>s.source==='eh_labour'&&s.status==='error'));
 });
 await t.test('templates all compile',()=>{const ejs=require('ejs');function walk(d){for(const x of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,x.name);if(x.isDirectory())walk(p);else if(p.endsWith('.ejs'))ejs.compile(fs.readFileSync(p,'utf8'),{filename:p});}}walk(path.join(__dirname,'../views'));});
 } finally {global.fetch=originalFetch;await new Promise(r=>server.close(r));db.close();fs.rmSync(dir,{recursive:true,force:true});}
});
